### ISSUE TITLE
Framework returns incorrect status code for create many requests

### ISSUE THREAD

**Issue by bencart** [Access4Learning/sif3-framework-java#27]
This issue has 2 components.

1. DataModelResource currently returns 201 created as the status code for successfully received create many requests. From the [3.2.1 specification](http://specification.sifassociation.org/Implementation/Infrastructure/3.2.1/Documents/BaseArchitecture_3-2-1.pdf) create many should return 
> An HTTP Response with a status of 200 and a payload consisting of a single “createResponse” element.

2. ObjectServiceClient currently considers a 200 response to be an error response. This results in individual status codes being discarded.

**Comment by joerghuber** [comment]
Fixed. Available in NSIP/v0.12.0 branch. Will be pushed to master in the near future,

**Comment by joerghuber** [comment]
Fixed. Available in NSIP/v0.12.0 branch. Will be pushed to master in the near future,
