### ISSUE TITLE
Timestamp header is calculated incorrectly.

### ISSUE THREAD

**Issue by bencart** [Access4Learning/sif3-framework-java#32]
Currently when populating the Timestamp header the Framework uses ISO formatted local time with 'Z' appended to indicate GMT time. This means that the framework generates timestamps in the future or past depending on your local timezone eg.
At 2:21pm in Perth Australia on the  27th of November the Timestamp being generated is:
`2017-11-27T14:21:00Z`

the actual timestamp should be :
`2017-11-27T06:21:00Z`

**Comment by joerghuber** [comment]
Fixed. Currently in v0.13.0 branch.
