### ISSUE TITLE
Provider in Brokered Environment over eager properties validation.

### ISSUE THREAD

**Issue by bencart** [Access4Learning/sif3-framework-java#34]
At the moment in the properties file of a provider in a brokered environment you must supply one of :
env.connector.url
env.connector.url.secure

As far as I'm aware these properties are not used (or needed) for a provider in a brokered environment.

**Comment by joerghuber** [comment]
Fixed on nsip fork in v0.13.0. Will be pushed to this repository in the near future.

**Comment by joerghuber** [comment]
This is now merged to the master.
