### ISSUE TITLE
Improve Queue Reader Exception Handling 

### ISSUE THREAD

**Issue by bencart** [Access4Learning/sif3-framework-java#35]
Currently it is possible both in RemoteMessageQueueReader and LocalMessageConsumer for the framework to encounter an exception and then fall out of the `while(true)` loop that the framework is using to read the queues.

This can be confusing because the rest of your consumer can be working fine however it can get into a state where it is no longer checking the remote queue and or the local queue.

**Comment by joerghuber** [comment]
Fixed on nsip fork in v0.13.0. Will be pushed to this repository in the near future.

**Comment by joerghuber** [comment]
This is now merged to the master.
