### ISSUE TITLE
Remote message readers not stopping

### ISSUE THREAD

**Issue by bencart** [Access4Learning/sif3-framework-java#37]
When shutting down my consumers using ConsumerLoader.shutdown() none of the threads that poll the remote message queues are actually shut down. They continue to run until the application server is shutdown, even though they start failing because they no longer have access to the consumer credentials.

This is because the ConsumerLoader calls service.shutdown() which interrupts idle threads and waits for currently executing threads to become idle before executing them. The way the message readers are implemented using a while (true) loop means that they never become idle.

I believe if you change the call to be service.shutdownNow() this will interrupt currently executing threads and will fix this issue.

**Comment by joerghuber** [comment]
This is now merged to the master.
